baseURL = "https://www.juanvillela.me/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan Villela"

[author]
  name = "Juan Villela"
  email = "hello@juanvillela.me"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  social = "fourjuaneight"

[params.meta]
  description = "Juan Villela Front-End Developer"
  keywords = "coding, business, development, front-end"

[outputs]
  home = ["html"]

[params.google]
  analytics = "UA-119777735-2"