baseURL = "https://juanvillela.me"
languageCode = "en-us"
title = "Juan"
copyright = "2018 Juan"

enableRobotsTXT = "true"
enableEmoji = "true"

[params.meta]
  keywords = "juan"
  description = "This is for me, not you"

[outputs]
  home = ["html", "rss"]

[params.google.analytics]
    trackerID = "UA-103631497-2"